version: '3'

volumes:
  storage:

services:
  adventure:
    build: .
    depends_on:
      - 'database'
    ports:
      - '8080:8080'

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'storage:/data/db'
